[env]
DEFMT_LOG = "trace"

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[target.thumbv7em-none-eabihf]
runner = 'probe-rs run --chip STM32H743IITx --probe 1fc9:5601'

# [target.thumbv7em-none-eabihf]
# make `cargo run` execute programs on QEMU
# runner = "qemu-system-arm -cpu cortex-m7 -machine mps2-an500 -nographic -semihosting-config enable=on,target=native -kernel"
